"""Initial tables

Revision ID: 332e9d454996
Revises: 
Create Date: 2025-04-04 20:13:38.711643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '332e9d454996'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usermodels',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usermodels_email'), 'usermodels', ['email'], unique=True)
    op.create_table('accountmodels',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usermodels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorymodels',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usermodels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budgetmodels',
    sa.Column('limit', sa.Float(), nullable=False),
    sa.Column('period', sa.Enum('DAY', 'WEEK', 'MONTH', name='budgetperiod'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categorymodels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usermodels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deptmodels',
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('type', sa.Enum('DEBT', 'LOAN', name='debttype'), nullable=False),
    sa.Column('counterparty', sa.String(length=100), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('is_repaid', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accountmodels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usermodels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactionmodels',
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', 'TRANSFER', name='transactiontype'), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('debt_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accountmodels.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categorymodels.id'], ),
    sa.ForeignKeyConstraint(['debt_id'], ['deptmodels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usermodels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactionmodels')
    op.drop_table('deptmodels')
    op.drop_table('budgetmodels')
    op.drop_table('categorymodels')
    op.drop_table('accountmodels')
    op.drop_index(op.f('ix_usermodels_email'), table_name='usermodels')
    op.drop_table('usermodels')
    # ### end Alembic commands ###
